### ISSUE TITLE
I can't download avatar in Blender

### ISSUE THREAD

**Issue by witrix-web** [RobeSantoro/ReadyPlayerMe-Blender-Tools#2]
Good morning,
                     I have downloaded and installed the ReadyPlayerMe-Blender-Tools, I have entered the id code of the avatar I would like to download but the plugin is reporting an error, the error indicates that you need to download the blender file, so I can't download the avatar in blender can you please explain me how to proceed to download the avatar in T position.
Thank you

**Comment by RobeSantoro** [comment]
Hi @witrix-web ! Thank you for checking the addon. The addon tells you to save the blender file first. It's just a check to know where to download the glb.

Could you try again?

**Comment by witrix-web** [comment]
I can't download the avatar, I don't understand where the avatar is downloaded.
Thank you

**Comment by RobeSantoro** [comment]
What Version of Blender are you using?
The addon works with the 3.6.5 LTS.

1. Save the blender scene
2. Copy the avatar ID (e.g.: 63ac69548d4fc7b44d50de62) from ready player me website
3. Select T Pose
4. Click download

**Comment by witrix-web** [comment]
I installed version 3.6.5 entered the avatar id code but it always gives me the same error can you correct it ?
Thanks for the support

**Comment by RobeSantoro** [comment]
Please write what error you get. Here's how everything works.

https://github.com/RobeSantoro/ReadyPlayerMe-Blender-Tools/assets/1170571/c4c5e947-a71b-4225-8769-0691822a9d0e

**Comment by witrix-web** [comment]
Ok I solved it thank you
